$axure.loadCurrentPage({
  "url":"新增_编辑_2.html",
  "generationDate":new Date(1474468828307.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1be73bc3669f459b81b362d48864fae0",
    "type":"Axure:Page",
    "name":"新增/编辑",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cbc1acbe4ae5497394a050fb70092c24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":90},
            "size":{
              "width":1166,
              "height":840},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1baf727db2cb4772bf6a6e758a19ab7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":90},
                "size":{
                  "width":1166,
                  "height":840},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_1/u0.png"}},
{
          "id":"80d67f3b921a4edcbac74ac9c98717e5",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"523d9e41ad424507844d7d43feaabbc4"},
{
          "id":"861d0f0356b444d9accca99a37feefca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":103},
            "size":{
              "width":1120,
              "height":870}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55aeca95ea78439999f3b2395b3b265d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":103},
                "size":{
                  "width":1120,
                  "height":870}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u70.png"}},
{
          "id":"15c58084feb648559b5d25a0017b79b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":223,
              "y":103},
            "size":{
              "width":1120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9dd5e65d34548a3af75036b5f34978a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":223,
                  "y":103},
                "size":{
                  "width":1120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u72.png"}},
{
          "id":"46789593d5df4fb5bf48d12ad0c2df83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":253,
              "y":114},
            "size":{
              "width":137,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"230c1dd5e36d4e8d82574788e0d54cc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":253,
                  "y":114},
                "size":{
                  "width":137,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e647ddfa23db4dcb936ed09a38d6f6d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":290,
              "y":278},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1efe1e23c3f43558255604ac656b6c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":290,
                  "y":278},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d92802576ea4e448a40e54a028aac14",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":673},
            "size":{
              "width":100,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b4fa02c6bce4ffbb85f0ea402fe6c91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":673},
                "size":{
                  "width":100,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增_编辑_2/u78.png"}},
{
          "id":"1d289fb0efde435f9a299aee6b54baf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":374,
              "y":673},
            "size":{
              "width":100,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"daf61df140284c3b9ee46953eb796d7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":374,
                  "y":673},
                "size":{
                  "width":100,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增_编辑_2/u80.png"}},
{
          "id":"db4aff9f8ae34866b8ef51286afc028f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":272},
            "size":{
              "width":850,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ded32a8627794e7f82bba399d97936c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":500,
              "y":673},
            "size":{
              "width":100,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a89207e71b47fdb199855ff92dd727",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":500,
                  "y":673},
                "size":{
                  "width":100,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增_编辑_2/u80.png"}},
{
          "id":"e23df8d158bc4cbd857cefd5886256e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":291,
              "y":387},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1bc5c4979945f0b19764c7ccc786f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":291,
                  "y":387},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb7271fcd55845c4895fe2c0901473b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":383},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fec4d7b99a4b178060d877230aecb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":383},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增_编辑/u141.png"}},
{
          "id":"33b5efb88a304326bf8a1d4280374941",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":374,
              "y":526},
            "size":{
              "width":730,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7842c488a144b24befca19b16b6bdbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":374,
                  "y":526},
                "size":{
                  "width":730,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u89.png"}},
{
          "id":"5ee194bda39a48b68f39d05a36817996",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":565},
            "size":{
              "width":730,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b2f7c0d5ebe4ea09cf5fa1ca3dd02fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":565},
                "size":{
                  "width":730,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u91.png"}},
{
          "id":"1aa8e34501b54e709ce71c7a5779ae32",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":538},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ebf29fa2dce4ff8a3040ec32a72ef64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":440,
                  "y":538},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3055861c94bd4a6eae71387edd2403ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":581,
              "y":538},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e9a363e3c9343d796b77e7233cfa572",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":581,
                  "y":538},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"050e700afb2f465ca2d6ca6f8554e6c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":752,
              "y":538},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb8dc4fd2db44a5f8a1169c440251951",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":752,
                  "y":538},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70016d6a1e8142588957e26440b3b12f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":999,
              "y":538},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfd0b2818423432799be4bcd3d60131d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":999,
                  "y":538},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ec411be2b504c7d9ef1026260bf5138",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":545,
              "y":526},
            "size":{
              "width":10,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑/u106_line.png"}},
{
          "id":"30737b6fe50042e19c5f651a4b8ce640",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":654,
              "y":526},
            "size":{
              "width":10,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑/u106_line.png"}},
{
          "id":"2d093b0e5d9f407f8cf39aca0af6e925",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":834,
              "y":526},
            "size":{
              "width":10,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑/u106_line.png"}},
{
          "id":"b89410b9c6224011b4c45830e03a628e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":954,
              "y":577},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c25382d0d2443c6ae65696fe4f49b4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":954,
                  "y":577},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a920604b23b47f9a66cdb6a26114145",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":1038,
              "y":577},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"405096fd9a5245a7a9ebb9d5860c93a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":1038,
                  "y":577},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"caa1f579553848c985a679996961cd9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":674,
              "y":577},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffe15c02794f44a484b9e945d4944ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":674,
                  "y":577},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u108.png"}},
{
          "id":"635b9e76dc364c81b396a04693bf13a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":674,
              "y":577},
            "size":{
              "width":90,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d720c8b1867044a08cf0520215ab15aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":674,
                  "y":577},
                "size":{
                  "width":90,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u110.png"}},
{
          "id":"8c443a3defdb48d5ab123e206f37387a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":796,
              "y":577},
            "size":{
              "width":56,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac72e253143f4aea9a922558fccc8e95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":796,
                  "y":577},
                "size":{
                  "width":56,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a0f90a4ea0f4ee088c0f520e57cf9c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":424,
              "y":577},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb87b1a7ab2b4c56bc8b0af28c14c3a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":424,
                  "y":577},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1605ddbbaf0b4f9186437a558fef0d1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":582,
              "y":577},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11df0943fe784c30b39eb238e7f3b07d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":582,
                  "y":577},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bf8620255804162a6c7c45dbd2c75f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":374,
              "y":433},
            "size":{
              "width":310,
              "height":83}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c67e9589a524300892471f8d5361256",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":374,
                  "y":433},
                "size":{
                  "width":310,
                  "height":83}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增_编辑_2/u118.png"}},
{
          "id":"d945a5e9e40446b2b4fae7e2d15521b9",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":914,
              "y":526},
            "size":{
              "width":10,
              "height":79},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/新增_编辑/u106_line.png"}},
{
          "id":"c4fbb5a81dcc40d1af417dd96bc1a156",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":864,
              "y":539},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cab9da6affd4b5cb84b1dd01d14611a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":864,
                  "y":539},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eab029073e6141e99419ebd9aa29e0bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":875,
              "y":577},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8decfc74f78542588943c65bcaf16e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":875,
                  "y":577},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45ba2e8a9d5343f3a3331b38963a0707",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":290,
              "y":334},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d0afb85070eb4355986088fe03f2af9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":290,
                  "y":334},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1000b148d3ed441d953f237f2537735f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":327},
            "size":{
              "width":850,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"69c24f22d3854c1ab98e7782381cb329",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Regular', 'Heiti SC'",
            "fontSize":"12px",
            "fontWeight":"200",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":223,
              "y":388},
            "size":{
              "width":108,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab817c03c3af436b98883dfd0afdda8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Regular', 'Heiti SC'",
                "fontSize":"12px",
                "fontWeight":"200",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":223,
                  "y":388},
                "size":{
                  "width":108,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aab4b51bca804b8dbe65f71dc62c9381",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":290,
              "y":221},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dae31fc473e4206b8a50ea5d7cc1a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":290,
                  "y":221},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc7ba9d117694b439b2c4764828b1288",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":375,
              "y":214},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2aafc68212204fee9d6ab8969e137d6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":1405,
              "y":334},
            "size":{
              "width":74,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e97b361023744099a8572bfbdd074f8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":1405,
                  "y":334},
                "size":{
                  "width":74,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"abf90ebfde214628a08dd5450c868170",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":1490,
              "y":327},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"55373acf89ec474dae18def0e590d30b",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1230,
              "y":340}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7823c35ea2ec4b07b278ab5adfe12421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1230,
                  "y":340}},
              "adaptiveStyles":{
}}]},
{
          "id":"3cd79e5dcf3d46acb80fe80969f4728f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":1447,
              "y":286},
            "size":{
              "width":334,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f86bbbc79fa435bad115d42f5fc74ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":1447,
                  "y":286},
                "size":{
                  "width":334,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "523d9e41ad424507844d7d43feaabbc4":{
      "packageId":"523d9e41ad424507844d7d43feaabbc4",
      "type":"Axure:Master",
      "name":"后台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3d4e2ace199a477b881ec31422f2e9c7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":1366,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"977ea9a4240a4c6fa547687f97422304",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":1366,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u11.png"}},
{
            "id":"c24d77a8f0ba4786a59f280ac064016b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":79},
              "size":{
                "width":200,
                "height":621},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ffeb09e5b7da4133af84e8496bf7aab8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":79},
                  "size":{
                    "width":200,
                    "height":621},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u13.png"}},
{
            "id":"4ffc8d3e1f694ea9a9f767154ff0eb56",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7CCCCCCC},
              "location":{
                "x":20,
                "y":10},
              "size":{
                "width":160,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"377f6ff063b6435c9849d346bbcdf87e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7CCCCCCC},
                  "location":{
                    "x":20,
                    "y":10},
                  "size":{
                    "width":160,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u15.png"}},
{
            "id":"f2b72a319ee24425b0fa4e916cca1078",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1180,
                "y":28},
              "size":{
                "width":64,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a7f83ca5487f47c396a262451ee391ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1180,
                    "y":28},
                  "size":{
                    "width":64,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"981cfd1fff1b4e859d27fa4c0e040732",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1132,
                "y":21},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b28e7b8bd0704d16a0cfe83e97f1e6e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1132,
                    "y":21},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u19.png"}},
{
            "id":"c740fe8afec544bb95ac39561b789d9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1275,
                "y":28},
              "size":{
                "width":50,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b8d4824289d4e59aa8c0b24209c2193",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1275,
                    "y":28},
                  "size":{
                    "width":50,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"8782be8b00b94218aa697111ae139466",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "location":{
                "x":1249,
                "y":28},
              "size":{
                "width":24,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e2fff69f9e0e431785bafde4f82489ac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":1249,
                    "y":28},
                  "size":{
                    "width":24,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebdb84e5838d406285c1e052be51f315",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "horizontalAlignment":"right",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1026,
                "y":28},
              "size":{
                "width":84,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12148dabc30940a7a4e341d320d68219",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "horizontalAlignment":"right",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1026,
                    "y":28},
                  "size":{
                    "width":84,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"e232ed54da1b475bb5757fa9075fa78a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":79}},
            "adaptiveStyles":{
},
            "masterId":"1cb8f9bc89dd40838b13f631659d68e0"}]}},
    "1cb8f9bc89dd40838b13f631659d68e0":{
      "packageId":"1cb8f9bc89dd40838b13f631659d68e0",
      "type":"Axure:Master",
      "name":"侧边栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af190ef3ee4e46b1a4fc662b88148b89",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":0,
                "y":39},
              "size":{
                "width":200,
                "height":397}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dee88fd556044befaa2282635a4d5e0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":0,
                    "y":39},
                  "size":{
                    "width":200,
                    "height":397}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u28.png"}},
{
            "id":"eb4288d0b9984ad7958ed0acd0c309db",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":119},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82f43dccbbb64e5b92386fee162b8137",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":119},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"04a1c3420404461f901bf6fc6a6f142d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":115},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"208c6655b104449eaad0a2bc663e90e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3524cb11e0ae489a885e4ed61c899ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"eea24d14aaef42c8be91f78b1489e846",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":7},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c900acee75394e10b17a25f376d2627b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":7,
                    "y":7},
                  "size":{
                    "width":25,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u35.png"}},
{
            "id":"3be4cc81b08c49018b581ab7f8bfef10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":-1},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f9f4462743e493a92ca3aedd5d6a2a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":-1},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b4bf9eaad42f4a95a2a674d85b3220a8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":79},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32545c74d6d345fab1fd0e1200138106",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":79},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"86e1a64489be4be9bf2ca2f9556b10cc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":239},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ea76637c3b04ffe99d37e793ae2fd9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":239},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"33fd588718f94930963b82a7a5fde012",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":249},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e36872bb0474067a3c1759d68fd3454",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":249},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"b41a515f941243f6afeba8c70cbf6ba2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":239},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fef05032d1944ae9ba7182babf86c33d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":239},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5a5a64137e084fd8b7121bfb0076bf66",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":249},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4413213ba3c4c9da5662f612cb13df4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":249},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"9040ee04f8954a1f9de74ce42dd7b651",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":279},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7367d5bb19244f88a527754600779144",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":279},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"47fdf487e2014f2c8ecaadf17124c94d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":39},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9f75bf532f5484a8f48c7b949ccb4d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":39},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"348859ab30c7433caf7c331cd792333d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":49},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"76be27cb72ca43eeb2b87e500319beec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":49},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"3013cf0bbead408b9073b4d735012784",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":39},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a78566039de4290bcf9724ecc608d11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":39},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7e05424e724840d2ade32c3189ae0d18",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":49},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c19c0b29430d4c2d97e1e0ce6c07b581",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":49},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"1cd190b6bf51448c9f0264629db1b391",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":313},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"b4d4e5a004bc40b79dda10048fc5f8ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":319},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"875c0698c8dc4d02919a9be5bf817088",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":319},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c733bca915a4435399177c95c7e77814",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":352},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"9e8bb07052c14982a2501f72c97a5049",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":358},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f457f48f099a40deac146132f44c7051",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":358},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37d6469a7d5945dbae45dc4f790ec02f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":390},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"b3376c9e9a164df581640aa95919e3dc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":396},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9659e184550f47faaf860ced7033a80c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":396},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7493cacdbacc41c69d1fc6d5e8ad9243",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":159},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f65c0559387f4202b5191021a2bb4400",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":159},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"45fd42c0b48c4a01963cb1ad358f7177",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":169},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ecfb3b67054640d8b83a2a75756c3c04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":169},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"ff8a4412785645078515217eb6b878ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":159},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ee98f3bee4e4924be1e1dbb75c7ca4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":159},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6f3cad63982843268ef12d0798b695b9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":169},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a34c70a0c9184876aa198aa32e271eac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":169},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"aacec47775c24e89b74d9edffd8bf80f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":199},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ff1d2657a8a482e83ca174912a3e0cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":199},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "cbc1acbe4ae5497394a050fb70092c24":{
      "scriptId":"u0"},
    "1baf727db2cb4772bf6a6e758a19ab7a":{
      "scriptId":"u1"},
    "80d67f3b921a4edcbac74ac9c98717e5":{
      "scriptId":"u2",
      "3d4e2ace199a477b881ec31422f2e9c7":{
        "scriptId":"u3"},
      "977ea9a4240a4c6fa547687f97422304":{
        "scriptId":"u4"},
      "c24d77a8f0ba4786a59f280ac064016b":{
        "scriptId":"u5"},
      "ffeb09e5b7da4133af84e8496bf7aab8":{
        "scriptId":"u6"},
      "4ffc8d3e1f694ea9a9f767154ff0eb56":{
        "scriptId":"u7"},
      "377f6ff063b6435c9849d346bbcdf87e":{
        "scriptId":"u8"},
      "f2b72a319ee24425b0fa4e916cca1078":{
        "scriptId":"u9"},
      "a7f83ca5487f47c396a262451ee391ed":{
        "scriptId":"u10"},
      "981cfd1fff1b4e859d27fa4c0e040732":{
        "scriptId":"u11"},
      "b28e7b8bd0704d16a0cfe83e97f1e6e6":{
        "scriptId":"u12"},
      "c740fe8afec544bb95ac39561b789d9e":{
        "scriptId":"u13"},
      "8b8d4824289d4e59aa8c0b24209c2193":{
        "scriptId":"u14"},
      "8782be8b00b94218aa697111ae139466":{
        "scriptId":"u15"},
      "e2fff69f9e0e431785bafde4f82489ac":{
        "scriptId":"u16"},
      "ebdb84e5838d406285c1e052be51f315":{
        "scriptId":"u17"},
      "12148dabc30940a7a4e341d320d68219":{
        "scriptId":"u18"},
      "e232ed54da1b475bb5757fa9075fa78a":{
        "scriptId":"u19",
        "af190ef3ee4e46b1a4fc662b88148b89":{
          "scriptId":"u20"},
        "dee88fd556044befaa2282635a4d5e0f":{
          "scriptId":"u21"},
        "eb4288d0b9984ad7958ed0acd0c309db":{
          "scriptId":"u22"},
        "82f43dccbbb64e5b92386fee162b8137":{
          "scriptId":"u23"},
        "04a1c3420404461f901bf6fc6a6f142d":{
          "scriptId":"u24"},
        "208c6655b104449eaad0a2bc663e90e3":{
          "scriptId":"u25"},
        "3524cb11e0ae489a885e4ed61c899ffc":{
          "scriptId":"u26"},
        "eea24d14aaef42c8be91f78b1489e846":{
          "scriptId":"u27"},
        "c900acee75394e10b17a25f376d2627b":{
          "scriptId":"u28"},
        "3be4cc81b08c49018b581ab7f8bfef10":{
          "scriptId":"u29"},
        "8f9f4462743e493a92ca3aedd5d6a2a7":{
          "scriptId":"u30"},
        "b4bf9eaad42f4a95a2a674d85b3220a8":{
          "scriptId":"u31"},
        "32545c74d6d345fab1fd0e1200138106":{
          "scriptId":"u32"},
        "86e1a64489be4be9bf2ca2f9556b10cc":{
          "scriptId":"u33"},
        "9ea76637c3b04ffe99d37e793ae2fd9c":{
          "scriptId":"u34"},
        "33fd588718f94930963b82a7a5fde012":{
          "scriptId":"u35"},
        "9e36872bb0474067a3c1759d68fd3454":{
          "scriptId":"u36"},
        "b41a515f941243f6afeba8c70cbf6ba2":{
          "scriptId":"u37"},
        "fef05032d1944ae9ba7182babf86c33d":{
          "scriptId":"u38"},
        "5a5a64137e084fd8b7121bfb0076bf66":{
          "scriptId":"u39"},
        "d4413213ba3c4c9da5662f612cb13df4":{
          "scriptId":"u40"},
        "9040ee04f8954a1f9de74ce42dd7b651":{
          "scriptId":"u41"},
        "7367d5bb19244f88a527754600779144":{
          "scriptId":"u42"},
        "47fdf487e2014f2c8ecaadf17124c94d":{
          "scriptId":"u43"},
        "b9f75bf532f5484a8f48c7b949ccb4d1":{
          "scriptId":"u44"},
        "348859ab30c7433caf7c331cd792333d":{
          "scriptId":"u45"},
        "76be27cb72ca43eeb2b87e500319beec":{
          "scriptId":"u46"},
        "3013cf0bbead408b9073b4d735012784":{
          "scriptId":"u47"},
        "5a78566039de4290bcf9724ecc608d11":{
          "scriptId":"u48"},
        "7e05424e724840d2ade32c3189ae0d18":{
          "scriptId":"u49"},
        "c19c0b29430d4c2d97e1e0ce6c07b581":{
          "scriptId":"u50"},
        "1cd190b6bf51448c9f0264629db1b391":{
          "scriptId":"u51"},
        "b4d4e5a004bc40b79dda10048fc5f8ec":{
          "scriptId":"u52"},
        "875c0698c8dc4d02919a9be5bf817088":{
          "scriptId":"u53"},
        "c733bca915a4435399177c95c7e77814":{
          "scriptId":"u54"},
        "9e8bb07052c14982a2501f72c97a5049":{
          "scriptId":"u55"},
        "f457f48f099a40deac146132f44c7051":{
          "scriptId":"u56"},
        "37d6469a7d5945dbae45dc4f790ec02f":{
          "scriptId":"u57"},
        "b3376c9e9a164df581640aa95919e3dc":{
          "scriptId":"u58"},
        "9659e184550f47faaf860ced7033a80c":{
          "scriptId":"u59"},
        "7493cacdbacc41c69d1fc6d5e8ad9243":{
          "scriptId":"u60"},
        "f65c0559387f4202b5191021a2bb4400":{
          "scriptId":"u61"},
        "45fd42c0b48c4a01963cb1ad358f7177":{
          "scriptId":"u62"},
        "ecfb3b67054640d8b83a2a75756c3c04":{
          "scriptId":"u63"},
        "ff8a4412785645078515217eb6b878ed":{
          "scriptId":"u64"},
        "2ee98f3bee4e4924be1e1dbb75c7ca4f":{
          "scriptId":"u65"},
        "6f3cad63982843268ef12d0798b695b9":{
          "scriptId":"u66"},
        "a34c70a0c9184876aa198aa32e271eac":{
          "scriptId":"u67"},
        "aacec47775c24e89b74d9edffd8bf80f":{
          "scriptId":"u68"},
        "1ff1d2657a8a482e83ca174912a3e0cf":{
          "scriptId":"u69"}}},
    "861d0f0356b444d9accca99a37feefca":{
      "scriptId":"u70"},
    "55aeca95ea78439999f3b2395b3b265d":{
      "scriptId":"u71"},
    "15c58084feb648559b5d25a0017b79b5":{
      "scriptId":"u72"},
    "f9dd5e65d34548a3af75036b5f34978a":{
      "scriptId":"u73"},
    "46789593d5df4fb5bf48d12ad0c2df83":{
      "scriptId":"u74"},
    "230c1dd5e36d4e8d82574788e0d54cc3":{
      "scriptId":"u75"},
    "e647ddfa23db4dcb936ed09a38d6f6d5":{
      "scriptId":"u76"},
    "e1efe1e23c3f43558255604ac656b6c1":{
      "scriptId":"u77"},
    "9d92802576ea4e448a40e54a028aac14":{
      "scriptId":"u78"},
    "9b4fa02c6bce4ffbb85f0ea402fe6c91":{
      "scriptId":"u79"},
    "1d289fb0efde435f9a299aee6b54baf3":{
      "scriptId":"u80"},
    "daf61df140284c3b9ee46953eb796d7b":{
      "scriptId":"u81"},
    "db4aff9f8ae34866b8ef51286afc028f":{
      "scriptId":"u82"},
    "ded32a8627794e7f82bba399d97936c3":{
      "scriptId":"u83"},
    "80a89207e71b47fdb199855ff92dd727":{
      "scriptId":"u84"},
    "e23df8d158bc4cbd857cefd5886256e3":{
      "scriptId":"u85"},
    "5a1bc5c4979945f0b19764c7ccc786f1":{
      "scriptId":"u86"},
    "cb7271fcd55845c4895fe2c0901473b1":{
      "scriptId":"u87"},
    "80fec4d7b99a4b178060d877230aecb4":{
      "scriptId":"u88"},
    "33b5efb88a304326bf8a1d4280374941":{
      "scriptId":"u89"},
    "b7842c488a144b24befca19b16b6bdbc":{
      "scriptId":"u90"},
    "5ee194bda39a48b68f39d05a36817996":{
      "scriptId":"u91"},
    "6b2f7c0d5ebe4ea09cf5fa1ca3dd02fb":{
      "scriptId":"u92"},
    "1aa8e34501b54e709ce71c7a5779ae32":{
      "scriptId":"u93"},
    "1ebf29fa2dce4ff8a3040ec32a72ef64":{
      "scriptId":"u94"},
    "3055861c94bd4a6eae71387edd2403ae":{
      "scriptId":"u95"},
    "3e9a363e3c9343d796b77e7233cfa572":{
      "scriptId":"u96"},
    "050e700afb2f465ca2d6ca6f8554e6c9":{
      "scriptId":"u97"},
    "fb8dc4fd2db44a5f8a1169c440251951":{
      "scriptId":"u98"},
    "70016d6a1e8142588957e26440b3b12f":{
      "scriptId":"u99"},
    "dfd0b2818423432799be4bcd3d60131d":{
      "scriptId":"u100"},
    "4ec411be2b504c7d9ef1026260bf5138":{
      "scriptId":"u101"},
    "30737b6fe50042e19c5f651a4b8ce640":{
      "scriptId":"u102"},
    "2d093b0e5d9f407f8cf39aca0af6e925":{
      "scriptId":"u103"},
    "b89410b9c6224011b4c45830e03a628e":{
      "scriptId":"u104"},
    "7c25382d0d2443c6ae65696fe4f49b4b":{
      "scriptId":"u105"},
    "2a920604b23b47f9a66cdb6a26114145":{
      "scriptId":"u106"},
    "405096fd9a5245a7a9ebb9d5860c93a1":{
      "scriptId":"u107"},
    "caa1f579553848c985a679996961cd9d":{
      "scriptId":"u108"},
    "ffe15c02794f44a484b9e945d4944ba3":{
      "scriptId":"u109"},
    "635b9e76dc364c81b396a04693bf13a8":{
      "scriptId":"u110"},
    "d720c8b1867044a08cf0520215ab15aa":{
      "scriptId":"u111"},
    "8c443a3defdb48d5ab123e206f37387a":{
      "scriptId":"u112"},
    "ac72e253143f4aea9a922558fccc8e95":{
      "scriptId":"u113"},
    "3a0f90a4ea0f4ee088c0f520e57cf9c4":{
      "scriptId":"u114"},
    "cb87b1a7ab2b4c56bc8b0af28c14c3a7":{
      "scriptId":"u115"},
    "1605ddbbaf0b4f9186437a558fef0d1e":{
      "scriptId":"u116"},
    "11df0943fe784c30b39eb238e7f3b07d":{
      "scriptId":"u117"},
    "5bf8620255804162a6c7c45dbd2c75f7":{
      "scriptId":"u118"},
    "6c67e9589a524300892471f8d5361256":{
      "scriptId":"u119"},
    "d945a5e9e40446b2b4fae7e2d15521b9":{
      "scriptId":"u120"},
    "c4fbb5a81dcc40d1af417dd96bc1a156":{
      "scriptId":"u121"},
    "5cab9da6affd4b5cb84b1dd01d14611a":{
      "scriptId":"u122"},
    "eab029073e6141e99419ebd9aa29e0bf":{
      "scriptId":"u123"},
    "8decfc74f78542588943c65bcaf16e22":{
      "scriptId":"u124"},
    "45ba2e8a9d5343f3a3331b38963a0707":{
      "scriptId":"u125"},
    "d0afb85070eb4355986088fe03f2af9c":{
      "scriptId":"u126"},
    "1000b148d3ed441d953f237f2537735f":{
      "scriptId":"u127"},
    "69c24f22d3854c1ab98e7782381cb329":{
      "scriptId":"u128"},
    "ab817c03c3af436b98883dfd0afdda8f":{
      "scriptId":"u129"},
    "aab4b51bca804b8dbe65f71dc62c9381":{
      "scriptId":"u130"},
    "4dae31fc473e4206b8a50ea5d7cc1a02":{
      "scriptId":"u131"},
    "cc7ba9d117694b439b2c4764828b1288":{
      "scriptId":"u132"},
    "2aafc68212204fee9d6ab8969e137d6e":{
      "scriptId":"u133"},
    "e97b361023744099a8572bfbdd074f8e":{
      "scriptId":"u134"},
    "abf90ebfde214628a08dd5450c868170":{
      "scriptId":"u135"},
    "55373acf89ec474dae18def0e590d30b":{
      "scriptId":"u136"},
    "7823c35ea2ec4b07b278ab5adfe12421":{
      "scriptId":"u137"},
    "3cd79e5dcf3d46acb80fe80969f4728f":{
      "scriptId":"u138"},
    "1f86bbbc79fa435bad115d42f5fc74ec":{
      "scriptId":"u139"}}});