$axure.loadCurrentPage({
  "url":"入职数据管理.html",
  "generationDate":new Date(1474468828632.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1bc11a371f2044a3b9e719d05c6fe668",
    "type":"Axure:Page",
    "name":"入职数据管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7ea27cbc2fa44792b5e29adccbfb426f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":90},
            "size":{
              "width":1166,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"625d5646e707482b9887130782eaea77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":90},
                "size":{
                  "width":1166,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司列表/u0.png"}},
{
          "id":"26afa765ae614a91b295f5eee0501d7a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"523d9e41ad424507844d7d43feaabbc4"},
{
          "id":"def02a44054e46ff91dab20d0e45aca7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":100},
            "size":{
              "width":1120,
              "height":581},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39db80b6be7b45abbe32f16edbf852aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":100},
                "size":{
                  "width":1120,
                  "height":581},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司列表/u2.png"}},
{
          "id":"62d077b65ddf40e4a401c72c325627fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":233,
              "y":100},
            "size":{
              "width":1120,
              "height":45},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9a9f55c185947cebb16dcb0ca90ab22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":233,
                  "y":100},
                "size":{
                  "width":1120,
                  "height":45},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/公司列表/u4.png"}},
{
          "id":"9a9ee444f1ae4f5ea9d25607e4dc8c2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "location":{
              "x":260,
              "y":113},
            "size":{
              "width":226,
              "height":16},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15e124fc6ecc430cb994ccc85f079665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "location":{
                  "x":260,
                  "y":113},
                "size":{
                  "width":226,
                  "height":16},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aad96fd4821340efb650a578c7ae6282",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1273,
              "y":110},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3def46f918a4d87adf35c455edd2d89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1273,
                  "y":110},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公司列表/u8.png"}},
{
          "id":"6b6ae0a408b0415f98c152724ade4d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":371,
              "y":113},
            "size":{
              "width":79,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c40126f754524c4b96b605d40a6168a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":371,
                  "y":113},
                "size":{
                  "width":79,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a86b6fe16c7449c896e44c875663d91c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":1520,
              "y":110},
            "size":{
              "width":60,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fdbd51c906c45ea9d1a45c535ff6ee9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":1520,
                  "y":110},
                "size":{
                  "width":60,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示/隐藏部件",
                      "objectsToFades":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/公司列表/u8.png"}},
{
          "id":"7c063a50233b4ae88c099189f7671647",
          "label":"",
          "type":"connector",
          "styleType":"connector",
          "visible":true,
          "style":{
            "location":{
              "x":1333,
              "y":123},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84cae47baeef4dc598e0526b276766e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1333,
                  "y":123},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}]},
{
          "id":"4927e85b11014301826da1ead3947d4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":1423,
              "y":166},
            "size":{
              "width":300,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40d9546bff3645b0a285e94da34f1e22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1423,
                  "y":166},
                "size":{
                  "width":300,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a66ee1a8663c497196f1df1f7bc797f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":484,
              "y":226},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9993657df2c1460e8c5147d942e73c5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":484,
                  "y":226},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2705d39100764c7b8888f32c4eabca76",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":564,
              "y":216},
            "size":{
              "width":426,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"d62514b62394430f9d43d9d29d139b75",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":484,
              "y":280},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"942aebfdea2f497c8c4774579e3a316e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":484,
                  "y":280},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe4bfa037e1b43adb284b11da798f98d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":564,
              "y":270},
            "size":{
              "width":426,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"cd730ddc1c6848c9b0be9a7fb71534dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":484,
              "y":335},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c9197b7b0f84070adf425ebc258a1f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":484,
                  "y":335},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3bcf5e82c5ce4ce489244b237216967d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "disabled":true,
          "visible":true,
          "style":{
            "location":{
              "x":564,
              "y":325},
            "size":{
              "width":426,
              "height":35}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "523d9e41ad424507844d7d43feaabbc4":{
      "packageId":"523d9e41ad424507844d7d43feaabbc4",
      "type":"Axure:Master",
      "name":"后台",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"3d4e2ace199a477b881ec31422f2e9c7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":1366,
                "height":80},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"977ea9a4240a4c6fa547687f97422304",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":1366,
                    "height":80},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u11.png"}},
{
            "id":"c24d77a8f0ba4786a59f280ac064016b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "location":{
                "x":0,
                "y":79},
              "size":{
                "width":200,
                "height":621},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ffeb09e5b7da4133af84e8496bf7aab8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "location":{
                    "x":0,
                    "y":79},
                  "size":{
                    "width":200,
                    "height":621},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u13.png"}},
{
            "id":"4ffc8d3e1f694ea9a9f767154ff0eb56",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0x7CCCCCCC},
              "location":{
                "x":20,
                "y":10},
              "size":{
                "width":160,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"377f6ff063b6435c9849d346bbcdf87e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0x7CCCCCCC},
                  "location":{
                    "x":20,
                    "y":10},
                  "size":{
                    "width":160,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u15.png"}},
{
            "id":"f2b72a319ee24425b0fa4e916cca1078",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1180,
                "y":28},
              "size":{
                "width":64,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a7f83ca5487f47c396a262451ee391ed",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1180,
                    "y":28},
                  "size":{
                    "width":64,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"981cfd1fff1b4e859d27fa4c0e040732",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":1132,
                "y":21},
              "size":{
                "width":32,
                "height":32}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b28e7b8bd0704d16a0cfe83e97f1e6e6",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":1132,
                    "y":21},
                  "size":{
                    "width":32,
                    "height":32}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u19.png"}},
{
            "id":"c740fe8afec544bb95ac39561b789d9e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}},
                "selected":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1275,
                "y":28},
              "size":{
                "width":50,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8b8d4824289d4e59aa8c0b24209c2193",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}},
                    "selected":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1275,
                    "y":28},
                  "size":{
                    "width":50,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "selected~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"8782be8b00b94218aa697111ae139466",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontSize":"16px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "location":{
                "x":1249,
                "y":28},
              "size":{
                "width":24,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e2fff69f9e0e431785bafde4f82489ac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"16px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":1249,
                    "y":28},
                  "size":{
                    "width":24,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebdb84e5838d406285c1e052be51f315",
            "label":"",
            "type":"buttonShape",
            "styleType":"h2",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "horizontalAlignment":"right",
              "stateStyles":{
                "mouseOver":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":1026,
                "y":28},
              "size":{
                "width":84,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"12148dabc30940a7a4e341d320d68219",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "horizontalAlignment":"right",
                  "stateStyles":{
                    "mouseOver":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":1026,
                    "y":28},
                  "size":{
                    "width":84,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"e232ed54da1b475bb5757fa9075fa78a",
            "label":"",
            "type":"referenceDiagramObject",
            "styleType":"referenceDiagramObject",
            "visible":true,
            "style":{
              "location":{
                "x":0,
                "y":79}},
            "adaptiveStyles":{
},
            "masterId":"1cb8f9bc89dd40838b13f631659d68e0"}]}},
    "1cb8f9bc89dd40838b13f631659d68e0":{
      "packageId":"1cb8f9bc89dd40838b13f631659d68e0",
      "type":"Axure:Master",
      "name":"侧边栏",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"af190ef3ee4e46b1a4fc662b88148b89",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "location":{
                "x":0,
                "y":39},
              "size":{
                "width":200,
                "height":397}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dee88fd556044befaa2282635a4d5e0f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "location":{
                    "x":0,
                    "y":39},
                  "size":{
                    "width":200,
                    "height":397}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u28.png"}},
{
            "id":"eb4288d0b9984ad7958ed0acd0c309db",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":119},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"82f43dccbbb64e5b92386fee162b8137",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":119},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"04a1c3420404461f901bf6fc6a6f142d",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":115},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"208c6655b104449eaad0a2bc663e90e3",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3524cb11e0ae489a885e4ed61c899ffc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"eea24d14aaef42c8be91f78b1489e846",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":7,
                "y":7},
              "size":{
                "width":25,
                "height":25}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c900acee75394e10b17a25f376d2627b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":7,
                    "y":7},
                  "size":{
                    "width":25,
                    "height":25}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u35.png"}},
{
            "id":"3be4cc81b08c49018b581ab7f8bfef10",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":-1},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f9f4462743e493a92ca3aedd5d6a2a7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":-1},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b4bf9eaad42f4a95a2a674d85b3220a8",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":79},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"32545c74d6d345fab1fd0e1200138106",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":79},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"86e1a64489be4be9bf2ca2f9556b10cc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":239},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9ea76637c3b04ffe99d37e793ae2fd9c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":239},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"33fd588718f94930963b82a7a5fde012",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":249},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9e36872bb0474067a3c1759d68fd3454",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":249},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"b41a515f941243f6afeba8c70cbf6ba2",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":239},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"fef05032d1944ae9ba7182babf86c33d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":239},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"5a5a64137e084fd8b7121bfb0076bf66",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":249},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d4413213ba3c4c9da5662f612cb13df4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":249},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"9040ee04f8954a1f9de74ce42dd7b651",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":279},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7367d5bb19244f88a527754600779144",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":279},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"47fdf487e2014f2c8ecaadf17124c94d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":39},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b9f75bf532f5484a8f48c7b949ccb4d1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":39},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"348859ab30c7433caf7c331cd792333d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":49},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"76be27cb72ca43eeb2b87e500319beec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":49},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"3013cf0bbead408b9073b4d735012784",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":39},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5a78566039de4290bcf9724ecc608d11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":39},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7e05424e724840d2ade32c3189ae0d18",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":49},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c19c0b29430d4c2d97e1e0ce6c07b581",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":49},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"1cd190b6bf51448c9f0264629db1b391",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":313},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"b4d4e5a004bc40b79dda10048fc5f8ec",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":319},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"875c0698c8dc4d02919a9be5bf817088",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":319},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c733bca915a4435399177c95c7e77814",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":352},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"9e8bb07052c14982a2501f72c97a5049",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":358},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f457f48f099a40deac146132f44c7051",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":358},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"37d6469a7d5945dbae45dc4f790ec02f",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":20,
                "y":390},
              "size":{
                "width":160,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFE4E4E4}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/公司列表/u32_line.png"}},
{
            "id":"b3376c9e9a164df581640aa95919e3dc",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":396},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9659e184550f47faaf860ced7033a80c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":396},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7493cacdbacc41c69d1fc6d5e8ad9243",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "location":{
                "x":0,
                "y":159},
              "size":{
                "width":200,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f65c0559387f4202b5191021a2bb4400",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "location":{
                    "x":0,
                    "y":159},
                  "size":{
                    "width":200,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u33.png"}},
{
            "id":"45fd42c0b48c4a01963cb1ad358f7177",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":170,
                "y":169},
              "size":{
                "width":20,
                "height":20},
              "rotation":"90",
              "textRotation":"90"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ecfb3b67054640d8b83a2a75756c3c04",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":170,
                    "y":169},
                  "size":{
                    "width":20,
                    "height":20},
                  "rotation":"90",
                  "textRotation":"90"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u43.png"}},
{
            "id":"ff8a4412785645078515217eb6b878ed",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Arial Negreta', 'Arial'",
              "fontWeight":"700",
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":159},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2ee98f3bee4e4924be1e1dbb75c7ca4f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Negreta', 'Arial'",
                  "fontWeight":"700",
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":159},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"6f3cad63982843268ef12d0798b695b9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":9,
                "y":169},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a34c70a0c9184876aa198aa32e271eac",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":9,
                    "y":169},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/公司列表/u47.png"}},
{
            "id":"aacec47775c24e89b74d9edffd8bf80f",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "verticalAlignment":"middle",
              "location":{
                "x":40,
                "y":199},
              "size":{
                "width":160,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1ff1d2657a8a482e83ca174912a3e0cf",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "verticalAlignment":"middle",
                  "location":{
                    "x":40,
                    "y":199},
                  "size":{
                    "width":160,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 链接",
                        "target":{
                          "targetType":"page",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "7ea27cbc2fa44792b5e29adccbfb426f":{
      "scriptId":"u0"},
    "625d5646e707482b9887130782eaea77":{
      "scriptId":"u1"},
    "26afa765ae614a91b295f5eee0501d7a":{
      "scriptId":"u2",
      "3d4e2ace199a477b881ec31422f2e9c7":{
        "scriptId":"u3"},
      "977ea9a4240a4c6fa547687f97422304":{
        "scriptId":"u4"},
      "c24d77a8f0ba4786a59f280ac064016b":{
        "scriptId":"u5"},
      "ffeb09e5b7da4133af84e8496bf7aab8":{
        "scriptId":"u6"},
      "4ffc8d3e1f694ea9a9f767154ff0eb56":{
        "scriptId":"u7"},
      "377f6ff063b6435c9849d346bbcdf87e":{
        "scriptId":"u8"},
      "f2b72a319ee24425b0fa4e916cca1078":{
        "scriptId":"u9"},
      "a7f83ca5487f47c396a262451ee391ed":{
        "scriptId":"u10"},
      "981cfd1fff1b4e859d27fa4c0e040732":{
        "scriptId":"u11"},
      "b28e7b8bd0704d16a0cfe83e97f1e6e6":{
        "scriptId":"u12"},
      "c740fe8afec544bb95ac39561b789d9e":{
        "scriptId":"u13"},
      "8b8d4824289d4e59aa8c0b24209c2193":{
        "scriptId":"u14"},
      "8782be8b00b94218aa697111ae139466":{
        "scriptId":"u15"},
      "e2fff69f9e0e431785bafde4f82489ac":{
        "scriptId":"u16"},
      "ebdb84e5838d406285c1e052be51f315":{
        "scriptId":"u17"},
      "12148dabc30940a7a4e341d320d68219":{
        "scriptId":"u18"},
      "e232ed54da1b475bb5757fa9075fa78a":{
        "scriptId":"u19",
        "af190ef3ee4e46b1a4fc662b88148b89":{
          "scriptId":"u20"},
        "dee88fd556044befaa2282635a4d5e0f":{
          "scriptId":"u21"},
        "eb4288d0b9984ad7958ed0acd0c309db":{
          "scriptId":"u22"},
        "82f43dccbbb64e5b92386fee162b8137":{
          "scriptId":"u23"},
        "04a1c3420404461f901bf6fc6a6f142d":{
          "scriptId":"u24"},
        "208c6655b104449eaad0a2bc663e90e3":{
          "scriptId":"u25"},
        "3524cb11e0ae489a885e4ed61c899ffc":{
          "scriptId":"u26"},
        "eea24d14aaef42c8be91f78b1489e846":{
          "scriptId":"u27"},
        "c900acee75394e10b17a25f376d2627b":{
          "scriptId":"u28"},
        "3be4cc81b08c49018b581ab7f8bfef10":{
          "scriptId":"u29"},
        "8f9f4462743e493a92ca3aedd5d6a2a7":{
          "scriptId":"u30"},
        "b4bf9eaad42f4a95a2a674d85b3220a8":{
          "scriptId":"u31"},
        "32545c74d6d345fab1fd0e1200138106":{
          "scriptId":"u32"},
        "86e1a64489be4be9bf2ca2f9556b10cc":{
          "scriptId":"u33"},
        "9ea76637c3b04ffe99d37e793ae2fd9c":{
          "scriptId":"u34"},
        "33fd588718f94930963b82a7a5fde012":{
          "scriptId":"u35"},
        "9e36872bb0474067a3c1759d68fd3454":{
          "scriptId":"u36"},
        "b41a515f941243f6afeba8c70cbf6ba2":{
          "scriptId":"u37"},
        "fef05032d1944ae9ba7182babf86c33d":{
          "scriptId":"u38"},
        "5a5a64137e084fd8b7121bfb0076bf66":{
          "scriptId":"u39"},
        "d4413213ba3c4c9da5662f612cb13df4":{
          "scriptId":"u40"},
        "9040ee04f8954a1f9de74ce42dd7b651":{
          "scriptId":"u41"},
        "7367d5bb19244f88a527754600779144":{
          "scriptId":"u42"},
        "47fdf487e2014f2c8ecaadf17124c94d":{
          "scriptId":"u43"},
        "b9f75bf532f5484a8f48c7b949ccb4d1":{
          "scriptId":"u44"},
        "348859ab30c7433caf7c331cd792333d":{
          "scriptId":"u45"},
        "76be27cb72ca43eeb2b87e500319beec":{
          "scriptId":"u46"},
        "3013cf0bbead408b9073b4d735012784":{
          "scriptId":"u47"},
        "5a78566039de4290bcf9724ecc608d11":{
          "scriptId":"u48"},
        "7e05424e724840d2ade32c3189ae0d18":{
          "scriptId":"u49"},
        "c19c0b29430d4c2d97e1e0ce6c07b581":{
          "scriptId":"u50"},
        "1cd190b6bf51448c9f0264629db1b391":{
          "scriptId":"u51"},
        "b4d4e5a004bc40b79dda10048fc5f8ec":{
          "scriptId":"u52"},
        "875c0698c8dc4d02919a9be5bf817088":{
          "scriptId":"u53"},
        "c733bca915a4435399177c95c7e77814":{
          "scriptId":"u54"},
        "9e8bb07052c14982a2501f72c97a5049":{
          "scriptId":"u55"},
        "f457f48f099a40deac146132f44c7051":{
          "scriptId":"u56"},
        "37d6469a7d5945dbae45dc4f790ec02f":{
          "scriptId":"u57"},
        "b3376c9e9a164df581640aa95919e3dc":{
          "scriptId":"u58"},
        "9659e184550f47faaf860ced7033a80c":{
          "scriptId":"u59"},
        "7493cacdbacc41c69d1fc6d5e8ad9243":{
          "scriptId":"u60"},
        "f65c0559387f4202b5191021a2bb4400":{
          "scriptId":"u61"},
        "45fd42c0b48c4a01963cb1ad358f7177":{
          "scriptId":"u62"},
        "ecfb3b67054640d8b83a2a75756c3c04":{
          "scriptId":"u63"},
        "ff8a4412785645078515217eb6b878ed":{
          "scriptId":"u64"},
        "2ee98f3bee4e4924be1e1dbb75c7ca4f":{
          "scriptId":"u65"},
        "6f3cad63982843268ef12d0798b695b9":{
          "scriptId":"u66"},
        "a34c70a0c9184876aa198aa32e271eac":{
          "scriptId":"u67"},
        "aacec47775c24e89b74d9edffd8bf80f":{
          "scriptId":"u68"},
        "1ff1d2657a8a482e83ca174912a3e0cf":{
          "scriptId":"u69"}}},
    "def02a44054e46ff91dab20d0e45aca7":{
      "scriptId":"u70"},
    "39db80b6be7b45abbe32f16edbf852aa":{
      "scriptId":"u71"},
    "62d077b65ddf40e4a401c72c325627fa":{
      "scriptId":"u72"},
    "c9a9f55c185947cebb16dcb0ca90ab22":{
      "scriptId":"u73"},
    "9a9ee444f1ae4f5ea9d25607e4dc8c2d":{
      "scriptId":"u74"},
    "15e124fc6ecc430cb994ccc85f079665":{
      "scriptId":"u75"},
    "aad96fd4821340efb650a578c7ae6282":{
      "scriptId":"u76"},
    "e3def46f918a4d87adf35c455edd2d89":{
      "scriptId":"u77"},
    "6b6ae0a408b0415f98c152724ade4d2b":{
      "scriptId":"u78"},
    "c40126f754524c4b96b605d40a6168a4":{
      "scriptId":"u79"},
    "a86b6fe16c7449c896e44c875663d91c":{
      "scriptId":"u80"},
    "9fdbd51c906c45ea9d1a45c535ff6ee9":{
      "scriptId":"u81"},
    "7c063a50233b4ae88c099189f7671647":{
      "scriptId":"u82"},
    "84cae47baeef4dc598e0526b276766e5":{
      "scriptId":"u83"},
    "4927e85b11014301826da1ead3947d4c":{
      "scriptId":"u84"},
    "40d9546bff3645b0a285e94da34f1e22":{
      "scriptId":"u85"},
    "a66ee1a8663c497196f1df1f7bc797f6":{
      "scriptId":"u86"},
    "9993657df2c1460e8c5147d942e73c5f":{
      "scriptId":"u87"},
    "2705d39100764c7b8888f32c4eabca76":{
      "scriptId":"u88"},
    "d62514b62394430f9d43d9d29d139b75":{
      "scriptId":"u89"},
    "942aebfdea2f497c8c4774579e3a316e":{
      "scriptId":"u90"},
    "fe4bfa037e1b43adb284b11da798f98d":{
      "scriptId":"u91"},
    "cd730ddc1c6848c9b0be9a7fb71534dd":{
      "scriptId":"u92"},
    "1c9197b7b0f84070adf425ebc258a1f4":{
      "scriptId":"u93"},
    "3bcf5e82c5ce4ce489244b237216967d":{
      "scriptId":"u94"}}});