try {
/* module-key = 'com.atlassian.support.stp:stp-license-status-resources', location = 'js/stp-licenseStatus.js' */
(function(b){var a={destroyBanner:function(){AJS.$("#stp-licenseStatus-banner").slideUp(function(){AJS.$("#stp-licenseStatus-banner").remove()})},remindMeNever:function(c){c.preventDefault();AJS.$.ajax({type:"POST",async:true,url:AJS.contextPath()+"/rest/stp/1.0/license/remindMeNever"});a.destroyBanner()},remindMeLater:function(){AJS.$.ajax({type:"POST",async:true,url:AJS.contextPath()+"/rest/stp/1.0/license/remindMeLater"});a.destroyBanner()},recordOutboundLink:function(c,d){var e=e||[];e.push(["_setAccount",c],["_setCampSourceKey","STP"],["_setCampMediumKey","renewals_reminder"],["_setCampNameKey",d],["_trackEvent","renewal"])},createBanner:function(){AJS.$.ajax({type:"GET",dataType:"json",async:true,url:AJS.contextPath()+"/rest/stp/1.0/license/status",statusCode:{200:function(f){var c="\n<div id='stp-licenseStatus-banner'>\n";var e=f.daysToExpiry;var d="http://www.atlassian.com/company/contact?utm_source=STP&utm_medium=renewals_reminder&utm_campaign=";var g="http://www.my.atlassian.com?utm_source=STP&utm_medium=renewals_reminder&utm_campaign=";if(e<=30&&e>14){licenseLink=d+"renewals_30_reminder";c+=AJS.format("Your {0} license maintenance expires in {1} days. {2}Contact Atlassian{3} or {4}remind me later{5}.",f.productName,30,"<a id='stp-licenseStatus-contactAtlassian' target='_blank' href=\""+licenseLink+'">',"</a>","<a id='stp-licenseStatus-remindMeLater' href='#'>","</a>");c+="\n<button id='stp-licenseStatus-remindMeNever'>&#x2716;</button>"}else{if(e<=14&&e>7){licenseLink=d+"renewals_14_reminder";c+=AJS.format("You will lose access to Support and Updates for {0} in {1} days. {2}Contact Atlassian{3} or {4}remind me later{5}.",f.productName,14,"<a id='stp-licenseStatus-contactAtlassian' target='_blank' href=\""+licenseLink+'">',"</a>","<a id='stp-licenseStatus-remindMeLater' href='#'>","</a>")}else{if(e<=7){licenseLink=g+"renewals_7_reminder";c+=AJS.format("Your {0} Support and Updates access expires in {1} days. You can renew via {2}my.atlassian.com{3}.",f.productName,7,"<a id='stp-licenseStatus-renewNow' target='_blank' href=\""+licenseLink+'">',"</a>");c+="\n<button id='stp-licenseStatus-remindMeNever'>&#x2716;</button>"}}}c+="\n</div>";b(c).prependTo(document.body);AJS.$("#stp-licenseStatus-remindMeNever").click(a.remindMeNever);AJS.$("#stp-licenseStatus-remindMeLater").click(function(h){h.preventDefault();a.remindMeLater()});AJS.$("#stp-licenseStatus-contactAtlassian").click(function(h){a.remindMeLater()});AJS.$("#stp-licenseStatus-renewNow").click(function(h){a.remindMeLater()})}}})}};AJS.$(document).ready(function(){b("#stp-licenseStatus-banner").length||a.createBanner()})})(AJS.$);
} catch (err) {
    if (console && console.log && console.error) {
        console.log("Error running batched script.");
        console.error(err);
    }
}


